[config]
schemaVersion = "0.0.1"

[package]
namespace = "Trodi"
name = "BloodyBoss"
versionNumber = "1.1.0"
description = "BloodyBoss is a mod for V Rising that allows you to create VBlood world bosses with random rewards that can be set for each of the world bosses."
websiteUrl = "https://github.com/oscarpedrero/BloodyBoss"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_V_Rising = "1.668.5"
deca-Bloodstone = "0.2.2"
deca-VampireCommandFramework = "0.9.0"
Trodi-BloodyCore = "1.2.4"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./dist"
target = ""

[publish]
communities = ["v-rising"]
repository = "https://thunderstore.io"
[publish.categories]
v-rising = ["1-0-update", "mods", "server"]